%% Import data from text file.
% Script for importing data from the following text file:
%
%    /Users/jesseschreger/Documents/CostOfSovereignDefault/Seasonal/Seasonal.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2015/08/20 15:32:19

%% Initialize variables.
filename = '/Users/jesseschreger/Documents/CostOfSovereignDefault/Seasonal/Seasonal.csv';
delimiter = ',';
startRow = 2;

%% Format string for each line of text:
%   column1: text (%s)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
%   column13: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines' ,startRow-1, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
quarter = dataArray{:, 1};
GDP_Deflator = dataArray{:, 2};
GDP_Deflator_change = dataArray{:, 3};
Nominal_GDP = dataArray{:, 4};
Nominal_GDP_GFD = dataArray{:, 5};
Nominal_GDP_GFD_change = dataArray{:, 6};
Nominal_GDP_change = dataArray{:, 7};
Real_GDP = dataArray{:, 8};
Real_GDP_change = dataArray{:, 9};
cpi = dataArray{:, 10};
inflation = dataArray{:, 11};
us_cpi = dataArray{:, 12};
us_inflation = dataArray{:, 13};


%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;


qtest=datenum(quarter,'yyyyqq');
qstring=datestr(qtest)

 spec = makespec('DIAG','AUTO','TRAMO','AO');
 x=x13([qtest,Nominal_GDP],spec)

